name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: gd
          tools: composer
      - run: composer install
      - run: composer run test
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          platforms: linux/arm64, linux/amd64
          tags: stefanhuber/fakeimage:latest



